spring.application.name=Security
server.port=8080

# segredo do JWT (mínimo 32 chars se for HS256/HS512; aqui vou usar HS256 com chave forte)
app.jwt.secret=coloca-uma-chave-grande-aqui-com-mais-de-32-caracteres
app.jwt.expMinutes=60

# cookie
app.cookie.name=AUTH_TOKEN
app.cookie.secure=false