spring.application.name=Security
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# segredo do JWT (mínimo 32 chars se for HS256/HS512; aqui vou usar HS256 com chave forte)
app.jwt.secret=coloca-uma-chave-grande-aqui-com-mais-de-32-caracteres
app.jwt.accessExpMinutes=1
app.jwt.refreshExpDays=7

# cookie
app.cookie.accessName=ACCESS_TOKEN
app.cookie.refreshName=REFRESH_TOKEN
app.cookie.secure=false